# Generated by Django 5.2.4 on 2025-12-11 06:23

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('br_request_date', models.DateField(verbose_name='BR Request Date')),
                ('br_date', models.DateField(verbose_name='BR Date')),
                ('bid_due_date', models.DateField(verbose_name='Bid Due Date')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex'), ('highly_complex', 'Highly Complex')], default='moderate', max_length=20)),
                ('business_unit', models.CharField(choices=[('JIS', 'JIS'), ('JCS', 'JCS')], max_length=10)),
                ('bid_level', models.CharField(choices=[('A', 'A Level - Strategic'), ('B', 'B Level - Major'), ('C', 'C Level - Standard'), ('D', 'D Level - Minor')], default='C', max_length=10)),
                ('bid_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated profit margin percentage', max_digits=5, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('technical_review', 'Technical Review'), ('commercial_review', 'Commercial Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('win_probability', models.DecimalField(blank=True, decimal_places=2, help_text='ML predicted win probability (%)', max_digits=5, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='ML calculated risk score (0-100)', max_digits=5, null=True)),
                ('complexity_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI assessed complexity score', max_digits=5, null=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=list, help_text='AI generated recommendations')),
                ('ml_features', models.JSONField(blank=True, default=dict, help_text='Features used for ML predictions')),
                ('requirements', models.JSONField(blank=True, default=dict, help_text='Structured requirements')),
                ('comments', models.TextField(blank=True)),
                ('winner', models.CharField(blank=True, max_length=200)),
                ('rfp_document', models.FileField(blank=True, null=True, upload_to='rfp_documents/')),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='proposals/')),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('review_cycle', models.IntegerField(default=1)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('total_edits', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('time_to_submit', models.DurationField(blank=True, null=True)),
                ('time_to_decision', models.DurationField(blank=True, null=True)),
                ('review_cycle_time', models.DurationField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pattern_insights', models.JSONField(blank=True, default=dict)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('value_history', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code_prefix', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bid Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BidMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='BidReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('technical', 'Technical Review'), ('commercial', 'Commercial Review'), ('legal', 'Legal Review'), ('financial', 'Financial Review'), ('risk', 'Risk Assessment'), ('final', 'Final Review')], max_length=20)),
                ('sequence', models.IntegerField(default=1)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('approved_comments', 'Approved with Comments'), ('modifications_required', 'Modifications Required'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=30, null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('ai_suggestions', models.TextField(blank=True)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('customer_type', models.CharField(choices=[('government', 'Government'), ('corporate', 'Corporate'), ('sme', 'SME'), ('individual', 'Individual')], default='corporate', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=10)),
                ('relationship_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_interaction', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
