# Generated by Django 5.2.4 on 2025-12-11 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='bids_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidanalytics',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.bidcategory'),
        ),
        migrations.AddField(
            model_name='bid',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.bidcategory'),
        ),
        migrations.AddField(
            model_name='bidmilestone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidmilestone',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidreview',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidreview',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='bidreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='bids_custom_name_9c63fc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='bids_custom_custome_86d756_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['industry'], name='bids_custom_industr_bcf252_idx'),
        ),
        migrations.AddField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='bids.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='bidreview',
            unique_together={('bid', 'review_type', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['code'], name='bids_bid_code_65a3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status'], name='bids_bid_status_071bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['bid_due_date'], name='bids_bid_bid_due_d367ce_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['business_unit'], name='bids_bid_busines_b42ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['priority'], name='bids_bid_priorit_ec1ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['win_probability'], name='bids_bid_win_pro_7a2b58_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['created_at'], name='bids_bid_created_3cd9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['customer', 'created_at'], name='bids_bid_custome_336c21_idx'),
        ),
    ]
