# Generated by Django 5.2.4 on 2025-12-11 06:23

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('bid_manager', 'Bid Manager'), ('reviewer', 'Reviewer'), ('analyst', 'Business Analyst'), ('viewer', 'Viewer'), ('sales', 'Sales Executive')], default='viewer', max_length=20, verbose_name='User Role')),
                ('business_unit', models.CharField(choices=[('JIS', 'JIS Business Unit'), ('JCS', 'JCS Business Unit'), ('all', 'All Business Units')], default='all', max_length=10, verbose_name='Business Unit')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('requires_password_change', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['username'], name='users_user_usernam_65d164_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx'), models.Index(fields=['business_unit'], name='users_user_busines_d49a8b_idx'), models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx')],
            },
        ),
    ]
