# Generated by Django 5.2.4 on 2025-12-23 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professional',
            field=models.BooleanField(default=False, verbose_name='Professional User'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_bio',
            field=models.TextField(blank=True, verbose_name='Professional Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Professional Title'),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_bid_notifications', models.BooleanField(default=True, help_text='Receive notifications for professional bid activities', verbose_name='Professional Bid Notifications')),
                ('professional_review_notifications', models.BooleanField(default=True, help_text='Receive notifications for professional review requests', verbose_name='Professional Review Notifications')),
                ('professional_deadline_notifications', models.BooleanField(default=True, help_text='Receive professional deadline reminders', verbose_name='Professional Deadline Notifications')),
                ('enabled_notifications', models.JSONField(blank=True, default=list, help_text='List of enabled notification types')),
                ('email_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('professional_email_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20, verbose_name='Professional Email Frequency')),
                ('professional_priority_threshold', models.CharField(choices=[('all', 'All Notifications'), ('high', 'High Priority Only'), ('critical', 'Critical Only')], default='high', max_length=20, verbose_name='Professional Priority Threshold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
