# Generated by Django 5.2.4 on 2025-12-24 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_professional_user_professional_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bid_assigned', 'Bid Assigned'), ('bid_review', 'Bid Review Required'), ('bid_approved', 'Bid Approved'), ('bid_rejected', 'Bid Rejected'), ('bid_due_soon', 'Bid Due Soon'), ('bid_won', 'Bid Won'), ('bid_lost', 'Bid Lost'), ('deadline_reminder', 'Deadline Reminder'), ('system_update', 'System Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('bid_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'), models.Index(fields=['user', 'created_at'], name='users_notif_user_id_2c9cd4_idx'), models.Index(fields=['type'], name='users_notif_type_0792c9_idx'), models.Index(fields=['priority'], name='users_notif_priorit_29dabc_idx')],
            },
        ),
    ]
